/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Server = IDL.Record({
  'id' : Id,
  'members' : IDL.Vec(IDL.Principal),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'channels' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'id' : Id,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'channel' : IDL.Text,
});
export const Signal = IDL.Record({
  'id' : Id,
  'to' : IDL.Principal,
  'channelName' : IDL.Text,
  'from' : IDL.Principal,
  'timestamp' : Time,
  'payload' : IDL.Text,
  'signalType' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChannel' : IDL.Func([Id, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createServer' : IDL.Func([IDL.Text], [Id], []),
  'getAllServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannelMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMySignals' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], []),
  'getServerMembers' : IDL.Func([Id], [IDL.Vec(IDL.Principal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
  'getVoiceChannelPresence' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinServer' : IDL.Func([Id], [], []),
  'joinVoiceChannel' : IDL.Func([IDL.Text], [], []),
  'leaveVoiceChannel' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendSignal' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Server = IDL.Record({
    'id' : Id,
    'members' : IDL.Vec(IDL.Principal),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'channels' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'id' : Id,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'channel' : IDL.Text,
  });
  const Signal = IDL.Record({
    'id' : Id,
    'to' : IDL.Principal,
    'channelName' : IDL.Text,
    'from' : IDL.Principal,
    'timestamp' : Time,
    'payload' : IDL.Text,
    'signalType' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChannel' : IDL.Func([Id, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createServer' : IDL.Func([IDL.Text], [Id], []),
    'getAllServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannelMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getMySignals' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], []),
    'getServerMembers' : IDL.Func([Id], [IDL.Vec(IDL.Principal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserServers' : IDL.Func([], [IDL.Vec(Server)], ['query']),
    'getVoiceChannelPresence' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinServer' : IDL.Func([Id], [], []),
    'joinVoiceChannel' : IDL.Func([IDL.Text], [], []),
    'leaveVoiceChannel' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendSignal' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };