/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Id = bigint;
export interface Message {
  'id' : Id,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'channel' : string,
}
export interface Server {
  'id' : Id,
  'members' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'channels' : Array<string>,
  'timestamp' : Time,
}
export interface Signal {
  'id' : Id,
  'to' : Principal,
  'channelName' : string,
  'from' : Principal,
  'timestamp' : Time,
  'payload' : string,
  'signalType' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChannel' : ActorMethod<[Id, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createServer' : ActorMethod<[string], Id>,
  'getAllServers' : ActorMethod<[], Array<Server>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannelMessages' : ActorMethod<[string], Array<Message>>,
  'getMySignals' : ActorMethod<[string], Array<Signal>>,
  'getServerMembers' : ActorMethod<[Id], Array<Principal>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserServers' : ActorMethod<[], Array<Server>>,
  'getVoiceChannelPresence' : ActorMethod<[string], Array<Principal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinServer' : ActorMethod<[Id], undefined>,
  'joinVoiceChannel' : ActorMethod<[string], undefined>,
  'leaveVoiceChannel' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'sendSignal' : ActorMethod<[Principal, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];